/*
 * ssd1306.c
 *
 *  Created on: Aug 12, 2026
 *      Author: nazim
 */

#include "ssd1306.h"
//#include "i2c.h"
#include <string.h>

/*
 * SSD1306 framebuffer
 *
 * 128 x 64 pixels
 *
 * 128 * 64 / 8 = 1024 bytes
 */
static uint8_t SSD1306_Buffer[SSD1306_WIDTH * SSD1306_HEIGHT / 8];

static uint8_t CurrentX = 0;
static uint8_t CurrentY = 0;


/*
 * I2C handle generated by CubeMX.
 *
 * If CubeMX generated hi2c1 in main.c, this extern allows
 * this driver to use it.
 */
extern I2C_HandleTypeDef hi2c1;


/* ============================================================
 * 5x7 FONT
 * ============================================================
 *
 * Characters supported:
 *
 * Space
 * A-Z
 * 0-9
 * :
 * .
 * %
 * -
 *
 * Each character = 5 columns.
 *
 * Bit 0 = top pixel
 * Bit 6 = bottom pixel
 * ============================================================
 */

static const uint8_t Font_AZ[26][5] =
{
    {0x7E,0x11,0x11,0x11,0x7E}, // A
    {0x7F,0x49,0x49,0x49,0x36}, // B
    {0x3E,0x41,0x41,0x41,0x22}, // C
    {0x7F,0x41,0x41,0x22,0x1C}, // D
    {0x7F,0x49,0x49,0x49,0x41}, // E
    {0x7F,0x09,0x09,0x09,0x01}, // F
    {0x3E,0x41,0x49,0x49,0x7A}, // G
    {0x7F,0x08,0x08,0x08,0x7F}, // H
    {0x00,0x41,0x7F,0x41,0x00}, // I
    {0x20,0x40,0x41,0x3F,0x01}, // J
    {0x7F,0x08,0x14,0x22,0x41}, // K
    {0x7F,0x40,0x40,0x40,0x40}, // L
    {0x7F,0x02,0x0C,0x02,0x7F}, // M
    {0x7F,0x04,0x08,0x10,0x7F}, // N
    {0x3E,0x41,0x41,0x41,0x3E}, // O
    {0x7F,0x09,0x09,0x09,0x06}, // P
    {0x3E,0x41,0x51,0x21,0x5E}, // Q
    {0x7F,0x09,0x19,0x29,0x46}, // R
    {0x46,0x49,0x49,0x49,0x31}, // S
    {0x01,0x01,0x7F,0x01,0x01}, // T
    {0x3F,0x40,0x40,0x40,0x3F}, // U
    {0x1F,0x20,0x40,0x20,0x1F}, // V
    {0x7F,0x20,0x18,0x20,0x7F}, // W
    {0x63,0x14,0x08,0x14,0x63}, // X
    {0x07,0x08,0x70,0x08,0x07}, // Y
    {0x61,0x51,0x49,0x45,0x43}  // Z
};


static const uint8_t Font_09[10][5] =
{
    {0x3E,0x51,0x49,0x45,0x3E}, // 0
    {0x00,0x42,0x7F,0x40,0x00}, // 1
    {0x42,0x61,0x51,0x49,0x46}, // 2
    {0x21,0x41,0x45,0x4B,0x31}, // 3
    {0x18,0x14,0x12,0x7F,0x10}, // 4
    {0x27,0x45,0x45,0x45,0x39}, // 5
    {0x3C,0x4A,0x49,0x49,0x30}, // 6
    {0x01,0x71,0x09,0x05,0x03}, // 7
    {0x36,0x49,0x49,0x49,0x36}, // 8
    {0x06,0x49,0x49,0x29,0x1E}  // 9
};


/* ============================================================
 * Send command to SSD1306
 * ============================================================ */

static void SSD1306_WriteCommand(uint8_t command)
{
    uint8_t data[2];

    data[0] = 0x00;       // Control byte: command
    data[1] = command;

    HAL_I2C_Master_Transmit(
        &hi2c1,
        SSD1306_I2C_ADDR,
        data,
        2,
        HAL_MAX_DELAY
    );
}


/* ============================================================
 * Send data to SSD1306
 * ============================================================ */

static void SSD1306_WriteData(uint8_t *data, uint16_t size)
{
    uint8_t buffer[129];

    /*
     * First byte = control byte
     * 0x40 means following bytes are display data.
     */

    buffer[0] = 0x40;

    memcpy(&buffer[1], data, size);

    HAL_I2C_Master_Transmit(
        &hi2c1,
        SSD1306_I2C_ADDR,
        buffer,
        size + 1,
        HAL_MAX_DELAY
    );
}


/* ============================================================
 * SSD1306 Initialization
 * ============================================================ */

void SSD1306_Init(void)
{
//    HAL_Delay(10);

    SSD1306_WriteCommand(0xAE); // Display OFF

    SSD1306_WriteCommand(0x20); // Set Memory Addressing Mode
    SSD1306_WriteCommand(0x00); // Horizontal addressing mode

    SSD1306_WriteCommand(0xB0); // Page start address

    SSD1306_WriteCommand(0xC8); // COM Output Scan Direction

    SSD1306_WriteCommand(0x00); // Low column address
    SSD1306_WriteCommand(0x10); // High column address

    SSD1306_WriteCommand(0x40); // Start line address

    SSD1306_WriteCommand(0x81); // Contrast
    SSD1306_WriteCommand(0x7F);

    SSD1306_WriteCommand(0xA1); // Segment remap

    SSD1306_WriteCommand(0xA6); // Normal display

    SSD1306_WriteCommand(0xA8); // Multiplex ratio
    SSD1306_WriteCommand(0x3F);

    SSD1306_WriteCommand(0xA4); // Display follows RAM

    SSD1306_WriteCommand(0xD3); // Display offset
    SSD1306_WriteCommand(0x00);

    SSD1306_WriteCommand(0xD5); // Display clock
    SSD1306_WriteCommand(0x80);

    SSD1306_WriteCommand(0xD9); // Pre-charge period
    SSD1306_WriteCommand(0xF1);

    SSD1306_WriteCommand(0xDA); // COM pins
    SSD1306_WriteCommand(0x12);

    SSD1306_WriteCommand(0xDB); // VCOMH
    SSD1306_WriteCommand(0x40);

    SSD1306_WriteCommand(0x8D); // Charge pump
    SSD1306_WriteCommand(0x14);

    SSD1306_WriteCommand(0xAF); // Display ON

    SSD1306_Fill(SSD1306_COLOR_BLACK);

    SSD1306_UpdateScreen();
}


/* ============================================================
 * Clear / Fill framebuffer
 * ============================================================ */

void SSD1306_Fill(uint8_t color)
{
    memset(
        SSD1306_Buffer,
        color ? 0xFF : 0x00,
        sizeof(SSD1306_Buffer)
    );
}


/* ============================================================
 * Set cursor position
 * ============================================================ */

void SSD1306_GotoXY(uint8_t x, uint8_t y)
{
    CurrentX = x;
    CurrentY = y;
}


/* ============================================================
 * Draw one character
 * ============================================================ */

void SSD1306_DrawChar(char c)
{
    uint8_t i;
    uint8_t j;

    const uint8_t *glyph = NULL;

    uint8_t character[5];

    memset(character, 0, sizeof(character));


    /* Space */

    if (c == ' ')
    {
        return;
    }


    /* Uppercase letters */

    if (c >= 'A' && c <= 'Z')
    {
        glyph = Font_AZ[c - 'A'];

        for (i = 0; i < 5; i++)
        {
            character[i] = glyph[i];
        }
    }


    /* Numbers */

    else if (c >= '0' && c <= '9')
    {
        glyph = Font_09[c - '0'];

        for (i = 0; i < 5; i++)
        {
            character[i] = glyph[i];
        }
    }


    /* Colon */

    else if (c == ':')
    {
        character[0] = 0x00;
        character[1] = 0x36;
        character[2] = 0x36;
        character[3] = 0x00;
        character[4] = 0x00;
    }


    /* Period */

    else if (c == '.')
    {
        character[0] = 0x00;
        character[1] = 0x40;
        character[2] = 0x60;
        character[3] = 0x00;
        character[4] = 0x00;
    }


    /* Percent */

    else if (c == '%')
    {
        character[0] = 0x63;
        character[1] = 0x13;
        character[2] = 0x08;
        character[3] = 0x64;
        character[4] = 0x63;
    }


    /* Hyphen */

    else if (c == '-')
    {
        character[0] = 0x08;
        character[1] = 0x08;
        character[2] = 0x08;
        character[3] = 0x08;
        character[4] = 0x08;
    }


    else
    {
        return;
    }


    /*
     * Draw 5 columns
     */

    for (i = 0; i < 5; i++)
    {
        uint8_t line = character[i];

        for (j = 0; j < 7; j++)
        {
            if (line & (1 << j))
            {
                uint16_t index;

                uint8_t x = CurrentX + i;
                uint8_t y = CurrentY + j;

                if (x < SSD1306_WIDTH && y < SSD1306_HEIGHT)
                {
                    index =
                        x +
                        (y / 8) * SSD1306_WIDTH;

                    SSD1306_Buffer[index] |=
                        (1 << (y % 8));
                }
            }
        }
    }

    CurrentX += 6;

    if (CurrentX + 5 >= SSD1306_WIDTH)
    {
        CurrentX = 0;
        CurrentY += 8;
    }
}


/* ============================================================
 * Print string
 * ============================================================ */

void SSD1306_Puts(const char *str)
{
    while (*str)
    {
        SSD1306_DrawChar(*str);
        str++;
    }
}


/* ============================================================
 * Update physical SSD1306 display
 * ============================================================ */

void SSD1306_UpdateScreen(void)
{
    uint8_t page;

    for (page = 0; page < 8; page++)
    {
        /*
         * Select page
         */

        SSD1306_WriteCommand(0xB0 + page);

        /*
         * Set column address to 0
         */

        SSD1306_WriteCommand(0x00);
        SSD1306_WriteCommand(0x10);

        /*
         * Send 128 bytes for this page.
         */

        SSD1306_WriteData(
            &SSD1306_Buffer[SSD1306_WIDTH * page],
            SSD1306_WIDTH
        );
    }
}
